# Generated by Django 4.0.4 on 2022-05-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_price_pricee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=87716952079, verbose_name='Nomer')),
                ('number_people', models.CharField(choices=[('1-2', '1-2'), ('3-5', '3-5'), ('5-10', '5-10'), ('10-15', '10-15')], max_length=125)),
                ('demalys_orny', models.CharField(max_length=100)),
                ('oz_kalasy', models.CharField(choices=[('Shym', 'Shymkent'), ('Ala', 'Almaty'), ('As', 'Astana')], max_length=100)),
            ],
        ),
    ]
