# Generated by Django 4.0.4 on 2022-05-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esim', models.CharField(default='', max_length=255, verbose_name='Esimi')),
                ('nomer', models.IntegerField(default=87777777777, verbose_name='Nomeri')),
                ('kala', models.CharField(default='', max_length=255, verbose_name='Kalasy')),
                ('email', models.EmailField(blank=True, default='@gmail.com', max_length=254, verbose_name='Elektrondyk poshta')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('is_published', models.BooleanField(default=True, verbose_name='Kelisim')),
            ],
        ),
    ]
