# Generated by Django 4.0.4 on 2022-05-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_registration_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTravel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('location', models.CharField(default='', max_length=255, verbose_name='Ornalaskan zheri')),
                ('climate', models.CharField(max_length=255, verbose_name='Klimat')),
                ('flora', models.CharField(default='', max_length=255, verbose_name='Osimdik')),
                ('legend', models.CharField(default='', max_length=255, verbose_name='Angyz')),
            ],
        ),
    ]
