# Generated by Django 4.0.4 on 2022-05-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_infotravel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotravel',
            name='name',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Url'),
        ),
    ]
