# Generated by Django 4.0.4 on 2022-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_infotravel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotravel',
            name='image',
            field=models.ImageField(blank=True, default='default value', null=True, upload_to='img', verbose_name='Suret'),
        ),
    ]
