# Generated by Django 4.0.4 on 2022-05-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_infotravel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='infotravel',
            name='description',
            field=models.TextField(default='df'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infotravel',
            name='imagetag',
            field=models.ImageField(blank=True, default='default value', null=True, upload_to='img', verbose_name='Suretteg'),
        ),
        migrations.AddField(
            model_name='infotravel',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
        ),
    ]
