# Generated by Django 4.0.4 on 2022-05-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_infotravel_description_infotravel_imagetag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='pochta',
            field=models.EmailField(blank=True, default='@stu.sdu.edu.kz', max_length=254, verbose_name='Ushinshi Elektrondyk poshta'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, default='@stu.sdu.edu.kz', max_length=254, verbose_name='Elektrondyk poshta'),
        ),
    ]
